### ISSUE TITLE
Don't like episode title yet

### ISSUE THREAD

**Issue by mih** [myyoda/module-datalad#1]
"ReproIn: BIDS datasets straight from the MR scanner" reflects only the first part of the content

**Comment by yarikoptic** [comment]
yes indeed... didn't realize that  and that is where we would need a slide or two and 5 min to describe / point to reproin  :-/ since otherwise it is just 1 command invocation.  how long it takes? may be whle it is running we could present it?

**Comment by yarikoptic** [comment]
Actually we could present it very briefly -- I would just point, or include verbatim this section with two images https://github.com/repronim/reproin#overall-workflow  which gives full overview - that there is a naming convention, and we take DICOMs in .  And that is it

**Comment by mih** [comment]
Title now: "ReproIn/DataLad: A complete portable and reproducible fMRI study from scratch"
