### ISSUE TITLE
`bids` feels like a suboptimal dataset name

### ISSUE THREAD

**Issue by aqw** [myyoda/module-datalad#4]
Specifically referring to `_episodes/03-01-reproin.md`

I understand the desire for something generic, but in my opinion, the name poses two problems:
1) we are encouraging poor naming practices. BIDS is a layout rather than something that reflects the content, the actual data. It's simply a bad name choice.
2) it's confusing. In the context of this tutorial, we're overloading the word now. Such as: "The BIDS formatted `bids` dataset". Also, the `bids` dataset is not actually layed out according to BIDS (albeit, due to a lack of content) until data starts being converted. Only then does it start resembling a BIDS formatted dataset. It's a bit "cart before the horse", which in the context of a tutorial, can be confusing to those trying to figure out "what /is/ a BIDS formatted dataset."

Just my 2 cents.

---Alex

**Comment by mih** [comment]
I see the point, so maybe better go with the purpose of the data: `localizer_scans`

This would also introduce the domain of the example data early and not make it appear as a late surprise.

**Comment by aqw** [comment]
> This would also introduce the domain of the example data early and not make it appear as a late surprise.

@mih that's another good point.

Would you like me to go through and change it to `localizer_scans`, or do you already have plans to do so.

**Comment by mih** [comment]
Please do!
